Auth service
vr009/our-little-chatik pull request #3
Opened 2022-07-23 10:05 UTC by grusha229

MVP of authentication service implemented.

2022-07-23 20:24 UTC, vr009 commented
Don't forget about:

- [ ] swagger

- [ ] unit tests

- [ ] integration tests (postman will be ok for that purpose)

Github actions will be added later, after all.

2022-07-23 21:17 UTC, vr009 requested changes

2022-07-23 21:17 UTC, vr009 commented on internal/auth/internal/delivery/handler.go
> +	w.WriteHeader(http.StatusOK)
You have another const value - model.Deleted. Please, refactor your logic for using this value (looks not much to change in code).

2022-07-23 21:17 UTC, vr009 commented on internal/auth/internal/models/session.go
> +	ExpiredAt time.Time `json:"expired_at,omitempty"`
This field seems unused. It is needed to keep in mind that tokens must be expired one day. We need to use it in redis and here, in code. Fix it after all other fixes, please.

2022-07-23 21:17 UTC, vr009 commented on internal/auth/internal/repo/db.go
> +	token, err := uuid.NewUUID()
Well, uuid is actually not the best format for keeping tokens. We should look at some other solutions for generate tokens. 
At least, our requirements for the implementation:
- it should be a fixed length string (or slice of bytes)
- it must be generated fast

I have found this [tread](https://stackoverflow.com/questions/22892120/how-to-generate-a-random-string-of-a-fixed-length-in-go/22892986#22892986)

2022-07-23 21:17 UTC, vr009 commented on internal/auth/internal/repo/db.go
> +
Extra line, let's remove it.

2022-07-28 07:37 UTC, grusha229 commented on internal/auth/internal/repo/db.go
> +	fmt.Println(uuidFormString)
done

2022-07-28 07:37 UTC, grusha229 commented on internal/auth/internal/delivery/handler.go
> +	w.WriteHeader(http.StatusOK)
done

2022-07-28 07:37 UTC, grusha229 commented on internal/auth/internal/repo/db.go
> +	token, err := uuid.NewUUID()
done

2022-07-28 07:37 UTC, grusha229 commented on internal/auth/internal/repo/db.go
> +
done

2022-08-04 07:27 UTC, vr009 commented on internal/auth/internal/repo/db.go
> +	token, err := uuid.NewUUID()
We should also test if the collision is possible here. The benchmark for 100500 times of generating tokens fits here good. To be honestly, we could just calculate a hash from users id. Use [crypto package](https://pkg.go.dev/crypto) for this purpose.

2022-08-05 08:17 UTC, vr009 commented on internal/auth/internal/repo/db.go
> +	token := MD5(session.UserID.String())
That should be moved to usecase layer.

2022-08-11 11:16 UTC, vr009 commented
You have commited artifacts from your IDE, that files must not be here. Also you need to remove user_data service code.
You should remove it, squash commits and force push it here.

2022-09-10 11:54 UTC, vr009 commented
The PR needs to be rebased on `main` now.

2022-09-10 19:00 UTC, vr009 commented on internal/auth/internal/repo/db.go
> +	token := MD5(session.UserID.String())
Will be moved to issue as your tech debt.

2022-09-10 19:01 UTC, vr009 approved these changes
Tests, swagger and other issues will be moved to your tech debts.

2022-09-10 19:01 UTC, merged